### PR TITLE
Deprecate k8s dashboard

### PR DESCRIPTION
**Pull request by atsikham**
[This](https://github.com/epiphany-platform/e-structures/pull/9) PR should be merged first

### CODE REVIEW

**Comment by rpudlowski93** [comment]
LGTM - Dashboard removed properly but let's check the failed checks.

**Review by mkyc — CHANGES_REQUESTED** [review]
`github.com/epiphany-platform/e-structures` has to be released and then updated here in `go.mod`.

**Comment by atsikham** [comment]
Needs to be verified and merged after [this](https://github.com/epiphany-platform/e-structures/issues/10) issue is fixed.

**Comment by mkyc** [comment]
I believe this is unblocked since e-structures v0.0.7 was released. Important thing is to remove local `saveConfig()`, `loadConfig()`, `saveState()` and `loadState()` from `helpers.go` and use `save.AzKSConfig()`, `load.AzKSConfog()`, `load.State()` and `save.State()` from e-structures

**Comment by mkyc** [comment]
This PR would also probably directly related to #47

**Review by mkyc — COMMENTED** [review]
LGTM, but I'm co author ;)

**Comment by mkyc** [comment]
this PR also addresses #47

**Review by rpudlowski93 — APPROVED** [review]
LGTM ✅

**Review by seriva — APPROVED** [review]

**Review by mkyc — APPROVED** [review]

**Pull request merged**
